-- ******************* customer_details ****************************

INSERT INTO user_details VALUES(default,"Onkar","Shinde","onkar131097@gmail.com","U2FsdGVkX18d5JZ2Sk45sAoyPx+c1FmlrF1YdQTQzCk=","9579493957","admin",default,default,default,default);
INSERT INTO user_details VALUES(default,"Mahesh","kale","mahesh@gmail.com","U2FsdGVkX18d5JZ2Sk45sAoyPx+c1FmlrF1YdQTQzCk=","9325455958",default,default,default,default,default);
INSERT INTO user_details VALUES(default,"Sangram","Mane","sangram@gmail.com","U2FsdGVkX18d5JZ2Sk45sAoyPx+c1FmlrF1YdQTQzCk=","9333564859",default,default,default,default,default);
INSERT INTO user_details VALUES(default,"Sakshi","Sangame","sakshi@gmail.com","U2FsdGVkX18d5JZ2Sk45sAoyPx+c1FmlrF1YdQTQzCk=","7384985958",default,default,default,default,default);
INSERT INTO user_details VALUES(default,"Narayan","Suryavanshi","narayan@gmail.com","U2FsdGVkX18d5JZ2Sk45sAoyPx+c1FmlrF1YdQTQzCk=","9451458599",default,default,default,default,default);
INSERT INTO user_details VALUES(default,"Maldiv","Kukade","maldiv@gmail.com","U2FsdGVkX18d5JZ2Sk45sAoyPx+c1FmlrF1YdQTQzCk=","9358568558",default,default,default,default,default);
INSERT INTO user_details VALUES(default,"Narendra","Sonawane","narendra@gmail.com","U2FsdGVkX18d5JZ2Sk45sAoyPx+c1FmlrF1YdQTQzCk=","7200500266",default,default,default,default,default);
INSERT INTO user_details VALUES(default,"Vyanktesh","Donage","vyanktesh@gmail.com","U2FsdGVkX18d5JZ2Sk45sAoyPx+c1FmlrF1YdQTQzCk=","9456425958",default,default,default,default,default);
INSERT INTO user_details VALUES(default,"Lata","Bhosale","lata@gmail.com","U2FsdGVkX18d5JZ2Sk45sAoyPx+c1FmlrF1YdQTQzCk=","9578484800",default,default,default,default,default);
INSERT INTO user_details VALUES(default,"Shivraj","Mangale","Shivraj@gmail.com","U2FsdGVkX18d5JZ2Sk45sAoyPx+c1FmlrF1YdQTQzCk=","9545303872",default,default,default,default,default);

SELECT * FROM user_details;

-- ******************* user_address ****************************

INSERT INTO user_address  VALUES(default,"India","Maharashtra","Sangli","Sangli","Kalanagar, Bypass Road",301,416416,1,default,default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Sangli","Sangli","Kalanagar, Bypass Road",301,416416,1,"friend_home",default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Sangli","Sangli","Kalanagar, Bypass Road",301,416416,1,"work_place",default,default);

INSERT INTO user_address  VALUES(default,"India","Maharashtra","Aurangabad","Nagar","Kalanagar, ABC road, Nagar",32,410411,2,default,default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Aurangabad","Nagar","Kalanagar, ABC road, Nagar",32,410411,2,"friend_home",default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Aurangabad","Nagar","Kalanagar, ABC road, Nagar",32,410411,2,"work_place",default,default);

INSERT INTO user_address  VALUES(default,"India","Maharashtra","Sangli","Mhaisal","Mhaisal-Vijapur road",74,416415,3,default,default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Sangli","Mhaisal","Mhaisal-Vijapur road",74,416415,3,"friend_home",default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Sangli","Mhaisal","Mhaisal-Vijapur road",74,416415,3,"work_place",default,default);

INSERT INTO user_address  VALUES(default,"India","Maharashtra","Kolhapur","Jaysingpur","Khwaja Basti, Kolhapur Road, Kolhapur",420,411411,4,default,default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Kolhapur","Jaysingpur","Khwaja Basti, Kolhapur Road, Kolhapur",420,411411,4,"friend_home",default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Kolhapur","Jaysingpur","Khwaja Basti, Kolhapur Road, Kolhapur",420,411411,4,"work_place",default,default);

INSERT INTO user_address  VALUES(default,"India","Maharashtra","Kolhapur","Hatkanangale","Old Police Station, Kolhapur Road, Kolhapur",007,411409,5,default,default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Kolhapur","Hatkanangale","Old Police Station, Kolhapur Road, Kolhapur",007,411409,5,"friend_home",default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Kolhapur","Hatkanangale","Old Police Station, Kolhapur Road, Kolhapur",007,411409,5,"work_place",default,default);

INSERT INTO user_address  VALUES(default,"India","Karnatak","Vijapur","Aalmatti","S. P. Patil School,Vikas Nagar, Vijapur",104,425410,6,default,default,default);
INSERT INTO user_address  VALUES(default,"India","Karnatak","Vijapur","Aalmatti","S. P. Patil School,Vikas Nagar, Vijapur",104,425410,6,"friend_home",default,default);
INSERT INTO user_address  VALUES(default,"India","Karnatak","Vijapur","Aalmatti","S. P. Patil School,Vikas Nagar, Vijapur",104,425410,6,"work_place",default,default);

INSERT INTO user_address  VALUES(default,"India","Maharashtra","Karad","karad","Sunbeam College road, Karad",107,411411,7,default,default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Karad","karad","Sunbeam College road, Karad",107,411411,7,"friend_home",default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Karad","karad","Sunbeam College road, Karad",107,411411,7,"work_place",default,default);

INSERT INTO user_address  VALUES(default,"India","Maharashtra","Kolhapur","Kagal","Karnatak-Kolhapur Border, NH-4 Highway, Kolhapur",401,411407,8,default,default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Kolhapur","Kagal","Karnatak-Kolhapur Border, NH-4 Highway, Kolhapur",401,411407,8,"friend_home",default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Kolhapur","Kagal","Karnatak-Kolhapur Border, NH-4 Highway, Kolhapur",401,411407,8,"work_place",default,default);

INSERT INTO user_address  VALUES(default,"India","Maharashtra","Sangli","Islampur","peth Naka, Peth-kolhapur Road, Kolhapur",100,411416,9,default,default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Sangli","Islampur","peth Naka, Peth-kolhapur Road, Kolhapur",100,411416,9,"friend_home",default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","Sangli","Islampr","peth Naka, Peth-kolhapur Road, Kolhapur",100,411416,9,"work_place",default,default);

INSERT INTO user_address  VALUES(default,"India","Maharashtra","ratnagiri","ratnagiri","Campus area, kokani chauk, ratnagiri",242,400413,10,default,default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","ratnagiri","ratnagiri","Campus area, kokani chauk, ratnagiri",242,400413,10,"friend_home",default,default);
INSERT INTO user_address  VALUES(default,"India","Maharashtra","ratnagiri","ratnagiri","Campus area, kokani chauk, ratnagiri",242,400413,10,"work_place",default,default);

SELECT * FROM user_address ORDER BY add_id;

-- ******************* brand_details ****************************

INSERT INTO brand_details  VALUES(default, "LAKME COSMETICS", "Lakme is one of the famous cosmetic brands of India, which was named after French opera Lakme. The company was started back in 1952, it is owned by HUL now. The company is mainly involved in colored cosmetics, suitable for Indian skin types. The main products are eyeliner, lipstick, maskara, skincare creams etc.",default,default,default);
INSERT INTO brand_details  VALUES(default, "LOTUS HERBALS PVT LTD", "Lotus Herbals Private Limited is an unlisted private company, it was incorporated on 20 September, 1993. Lotus Herbals manufactures and sells herbal formulation products to protect, heal, and enhance the face, the products are especially for skincare, makeup, facewash, toner, eyeliner, kajal, herbal cosmetics, cosmetic products, and powder.",default,default,default);
INSERT INTO brand_details  VALUES(default, "UNILEVER LIMITED​", "Unilever India Limited is an unlisted public company, the company was incorporated on 07 June, 2020. They supply essential cosmetic products designed for India and abroad. The company is a consumer goods company, that not only manufactures cosmetics but also sells home, food, and refreshment products in India and internationally.",default,default,default);
INSERT INTO brand_details  VALUES(default, 'L`ORÉAL', "L`ORÉAL India Private Limited is an unlisted private company, the company was incorporated on 19 February, 1991. The company manufactures cosmetics, beauty care products of skin care, make up, lip, selftan, hair care and color, face care, body care, sun care, fragrance, and beauty care products.",default,default,default);
INSERT INTO brand_details  VALUES(default, "COLORBAR", "Colorbar is one of the famous brands; based in India. The company was incorporated on 02 April, 2004. This is one of the PETA certified brands that markets cruelty-free product ranges like blushes and shimmers, foundations, compacts, and makeup removers and wipes for face; and liquid lip colors.",default,default,default);
INSERT INTO brand_details  VALUES(default, "MAYBELLINE", "Maybelline is one of the biggest names in cosmetic brands, the company is an American multinational cosmetic brand which is available in over 129 countries worldwide. Offering more than 200 products. Maybelline is subsidiary of L’Oréal. They offer a range of products like nail colors, lipsticks, eyeliners and many more makeup needs.",default,default,default);
INSERT INTO brand_details  VALUES(default, "LOTUS HERBALS", "Lotus was founded by Mr. Kamal Passi in the year 1993 with non-toxic cosmetics & beauty products online at Lotus Herbals. Lotus Herbal manufacture and sells a wide range of herbal formulation products to protect, heal, and enhance the face, body, and hair.",default,default,default);
INSERT INTO brand_details  VALUES(default, "BIOTECH", "Biotech is a well-known brand that manufactures Ayurvedic cosmetic & skincare products in India. The company is an unlisted public company that was incorporated on 15 March 2000. Biotech is a beauty & wellness company with a wide range of products for hair, skin, body, natural makeup, and many more.",default,default,default);
INSERT INTO brand_details  VALUES(default, "MAMAEARTH", "Mamaearth is another popular company based in India. The company operates as Honasa Consumer Limited; it is an unlisted public company incorporated on 16 September, 2016. Mamaearthoffers more than 300 safe and gentle baby care, body care, skincare, and hair care products in India.",default,default,default);
INSERT INTO brand_details  VALUES(default, "VELLVETTE LIFESTYLE PRIVATE LIMITED", "Vellvette Lifestyle Private Limited is the parent company of Sugar Cosmetics; it is an unlisted company, it was incorporated on 16 July, 2012. The company manufactures & manages cosmetic products and it operates as an online retail portal for cosmetic products. It offers hair, makeup, skincare, bath and body, and fragrance products.",default,default,default);

select * from brand_details;

-- ******************* category_details ****************************
-- oral care, skin care, sun care, hair care, decorative cosmetics, body care and perfumes.
INSERT INTO category_details  VALUES(default, 1, "oral care", "Cosmetic oral care products are used to clean teeth and the mouth, freshen breath, and maintain oral hygiene. They are generally made with cleaning agents and abrasive particles to remove plaque and stains, and with fluoride to protect against other issues.",default,default);
INSERT INTO category_details  VALUES(default, 1, "skin care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 1, "sun care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 1, "hair care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 1, "decorative cosmetics", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 1, "body care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 1, "perfumes", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);

INSERT INTO category_details  VALUES(default, 2, "oral care", "Cosmetic oral care products are used to clean teeth and the mouth, freshen breath, and maintain oral hygiene. They are generally made with cleaning agents and abrasive particles to remove plaque and stains, and with fluoride to protect against other issues.",default,default);
INSERT INTO category_details  VALUES(default, 2, "skin care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 2, "sun care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 2, "hair care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 2, "decorative cosmetics", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);

INSERT INTO category_details  VALUES(default, 3, "oral care", "Cosmetic oral care products are used to clean teeth and the mouth, freshen breath, and maintain oral hygiene. They are generally made with cleaning agents and abrasive particles to remove plaque and stains, and with fluoride to protect against other issues.",default,default);
INSERT INTO category_details  VALUES(default, 3, "skin care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 3, "sun care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 3, "perfumes", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);


INSERT INTO category_details  VALUES(default, 4, "sun care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 4, "hair care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 4, "decorative cosmetics", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 4, "body care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);

INSERT INTO category_details  VALUES(default, 5, "oral care", "Cosmetic oral care products are used to clean teeth and the mouth, freshen breath, and maintain oral hygiene. They are generally made with cleaning agents and abrasive particles to remove plaque and stains, and with fluoride to protect against other issues.",default,default);
INSERT INTO category_details  VALUES(default, 5, "skin care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 5, "sun care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);

INSERT INTO category_details  VALUES(default, 6, "hair care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 6, "decorative cosmetics", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 6, "body care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 6, "perfumes", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);

INSERT INTO category_details  VALUES(default, 7, "oral care", "Cosmetic oral care products are used to clean teeth and the mouth, freshen breath, and maintain oral hygiene. They are generally made with cleaning agents and abrasive particles to remove plaque and stains, and with fluoride to protect against other issues.",default,default);
INSERT INTO category_details  VALUES(default, 7, "skin care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 7, "sun care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 7, "hair care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 7, "decorative cosmetics", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);

INSERT INTO category_details  VALUES(default, 8, "body care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 8, "perfumes", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);

INSERT INTO category_details  VALUES(default, 9, "oral care", "Cosmetic oral care products are used to clean teeth and the mouth, freshen breath, and maintain oral hygiene. They are generally made with cleaning agents and abrasive particles to remove plaque and stains, and with fluoride to protect against other issues.",default,default);
INSERT INTO category_details  VALUES(default, 9, "skin care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 9, "sun care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 9, "hair care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 9, "decorative cosmetics", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 9, "body care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);

INSERT INTO category_details  VALUES(default, 10, "skin care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 10, "sun care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 10, "hair care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 10, "decorative cosmetics", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 10, "body care", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);
INSERT INTO category_details  VALUES(default, 10, "perfumes", "Cosmetic skin care products are substances or mixtures that are intended to be applied to the external parts of the human body to cleanse, protect, or beautify the skin. They can also be used to change one's appearance, such as by conceal blemishes, enhancing one's natural features, or adding color to the face.",default,default);

select * from category_details;

-- ******************* product_details ****************************

INSERT INTO product_details  VALUES(default, 1, "eMIST Mouth Freshener Spray", "A fresh breath to start the day is the best way to go! Aren't we right?Our fast-action eMIST mouth freshener spray is a unique blend of traditional Indian medicines and modern pharma technology that safeguards your oral hygiene. It helps in keeping your teeth and gums strong and eliminates bad breath to help you go about your day with full confidence! This mouth freshener spray is a potent blend of natural ingredients like clove, ginger, fennel, cinnamon & turmeric (Curcumin) in a refreshing camphor-menthol flavour.", default, 450, default, default);
INSERT INTO product_details  VALUES(default, 1, "eMIST Sleep Blend", "Tryptophan and Melatonin-enriched formula of the sleep spray regulates the quality and duration of your sleep by relieving stress and anxiety. The spray form under the tongue provides rapid relaxation by swiftly absorbing its calming ingredients.Enjoy undisturbed sleep with the Melatonin-enriched formula, paired with L-Tryptophan and L-Theanine promising overall well-being.The travel-friendly fast asleep spray ensures peaceful sleep transitions", default, 383, default, default);
INSERT INTO product_details  VALUES(default, 1, "A Mindful Gut", "Gut supplements that boost digestion and help relieve issues like gas and bloating Digestion supplements that enhance a healthy gut and provide relief from symptoms of acid reflux. Fast sleeping spray for boosting sleep quality and aiding insomnia. Deep sleep spray also provides relief from stress. Gift love and care in the form of a combo for your loved ones` birthdays. With the Mindful Gut combo, ensure your friends and family are cared for. This unique birthday combo enhances your overall well-being by focusing on the interrelated nature of the gut and mind. These products for sleep and gut, with a blend of powerful ingredients, allow you to experience a multi-faceted range of benefits.", default, 500, default, default);

select * from product_details;

-- ******************* cart ****************************

-- ******************* cart_details ****************************

-- ******************* bill_details ****************************

